nelmio_api_doc:
    documentation:
        info:
            title: Devconf API
            description: This is the API documentation for the Devconf API
            version: 1.0.0

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            security:
                - Bearer: []

    areas: # to filter documented areas
        path_patterns:
            # Exclude _profiler, _error, _wdt and /api/doc
            - ^/(?!doc|_profiler|_error|_wdt|exception).*

