security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        admin_api_user_provider:
            id: App\Security\AdminApiUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/
            access_token:
                token_handler: App\Security\AdminAccessTokenHandler
                token_extractors:
                    App\Security\AdminTokenExtractor
            provider: admin_api_user_provider

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/, role: PUBLIC_ACCESS }