services:
    php-fpm:
        build: docker/php-fpm
        container_name: dev-conferences-api-php-fpm
        restart: always
        working_dir: /application
        links:
            - "redis"
        volumes:
            - ~/.ssh:/root/.ssh:ro
            - ./:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini
            - ./docker/php-fpm/docker-www.conf:/etc/php/8.4/fpm/conf.d/docker-www.conf
        user: "1000:1000"
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - dev-conferences-traefik
            - dev-conferences-services

    webserver:
        image: nginx:alpine
        container_name: dev-conferences-api-webserver
        restart: always
        links:
            - 'php-fpm'
        working_dir: /application
        volumes:
            - ./:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - dev-conferences-certs:/certs
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=dev-conferences-traefik"
            - "traefik.http.routers.api.rule=Host(`api-devconf.traefik.me`)"
            - "traefik.http.routers.api.tls=true"
            - "traefik.http.services.api.loadbalancer.server.port=8080"
        networks:
            - dev-conferences-traefik
            - dev-conferences-services

    redis:
        image: redis:latest
        container_name: dev-conferences-api-redis
        restart: always
        networks:
            - dev-conferences-services

volumes:
    dev-conferences-certs:
        external: true

networks:
    dev-conferences-services:
        external: true
    dev-conferences-traefik:
        external: true
