# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Api\Client\YoutubeApiClient:
        arguments:
            $googleApiKey: '%env(GOOGLE_API_KEY)%'

    App\Service\Search\Client\MeilisearchClient:
        lazy: true
        arguments:
            $url: '%env(MEILISEARCH_URL)%'
            $apiKey: '%env(MEILISEARCH_API_KEY)%'

    App\Service\Search\Client\ElasticsearchClient:
        lazy: true
        arguments:
            $hosts:
                - '%env(ELASTICSEARCH_HOST)%'

    App\Service\Search\Client\AlgoliaClient:
        lazy: true
        arguments:
            $appId: '%env(ALGOLIA_APP_ID)%'
            $apiKey: '%env(ALGOLIA_API_KEY)%'

    slug_generator.conference_edition:
        class: App\Service\SlugGenerator
        arguments:
            $repository: '@App\Repository\ConferenceEditionRepository'

    slug_generator.talk:
        class: App\Service\SlugGenerator
        arguments:
            $repository: '@App\Repository\TalkRepository'

    slug_generator.speaker:
        class: App\Service\SlugGenerator
        arguments:
            $repository: '@App\Repository\SpeakerRepository'

    App\EventListener\CorsEventListener:
        tags:
            - { name: kernel.event_subscriber }

    App\Factory\SearchClientFactory: ~

    App\Service\Search\Client\SearchClientInterface:
        factory: ['@App\Factory\SearchClientFactory', 'create']
